##
## UNDER DEVELOPMENT
##

# Variables:
#vars:
#  firebase-project-id: "nuxt-apollo-hasura"

version: '3.6'
#services:
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword

  graphql-engine:
    image: hasura/graphql-engine:v1.2.2
    ports:
      - "4000:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      # Admin secret must be defined for Hasura JWT mode be enabled
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
      HASURA_GRAPHQL_ADMIN_SECRET: adminpassword
#      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS512", "key": "<AUTH_PUBLIC_KEY>"}'
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS512", "key": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsVdTpFbphTHAQSOhwiQS\nHhRD1krquC1dzlxGxpsLJJqIkPuLTwOrXpyJZwpUZhLkvoGa4Z+RxK3w+BkDyxFe\nRvOLPqrmJ3haobO8kTF/iLK5+TbLPKP6k8JOVgkFfqXHuRSD0zFGIMG3u8z7Q5kT\nniyfbv/QL0SIe1LpSm2KN5eKch81CgUm3BTd+R8OC2Qbxo3cFaTf3yNeTCsHDT/R\n78HZ3rMDEtyQzvHEgEeBEQx2NTAUXWiI/E504JBiXF67tlNYLKGU5bPwVtAGDCEJ\n8mgoSHZci2BYl/dTMT1nQ10WrTdChCEtqnKi4zOaHWnRJu29UKYslhILgs7U4Rvm\n+QIDAQAB\n-----END PUBLIC KEY-----\n"}'

volumes:
  db_data:

